services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - db
    # COMMANDS - Choose one based on your needs:

    # 1. DEBUGGING COMMAND (current): 
    #    Starts the application with the debugpy debugger, waiting for a client to attach.
    #    Uvicorn will use --reload for automatic code reloading.
    command: >
      sh -c "./wait-for-it.sh db:5432 --timeout=30 --strict -- \
      alembic upgrade head && \
      python scripts/create_admin.py && \
      python -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

    # 2. PRODUCTION-LIKE COMMAND (commented out):
    #    Starts the application directly with Uvicorn. No debugger, no auto-reload.
    #    For true production, ensure DEBUG environment variables are also appropriately set to False.
    # command: >
    #   sh -c \"./wait-for-it.sh db:5432 --timeout=30 --strict -- \
    #   alembic upgrade head && \
    #   python scripts/create_admin.py && \
    #   uvicorn app.main:app --host 0.0.0.0 --port 8000\"
    restart: always
    
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./backend/init-test-db.sh:/docker-entrypoint-initdb.d/init-test-db.sh
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=duelo_de_plumas
    restart: always
    
  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
      # Uncomment the next line if you want to use Chrome debugging with --remote-debugging-port
      # - "9222:9222"
      # Uncomment the next line if you want to debug the Vite dev server (Node.js debugging)
      # - "9229:9229"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      - backend
    restart: always
    # COMMANDS - Choose one based on your needs:
    
    # 1. DEVELOPMENT COMMAND (current):
    #    Standard Vite dev server with hot reload
    # This is handled by the Dockerfile CMD
    
    # 2. DEBUG COMMAND (alternative):
    #    For debugging Node.js side (Vite dev server itself)
    #    Uncomment to debug the Vite dev server process
    # command: >
    #   sh -c "node --inspect=0.0.0.0:9229 node_modules/vite/bin/vite.js --host 0.0.0.0 --port 3001"

volumes:
  postgres_data: 