services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - db
    command: >
      sh -c "./wait-for-it.sh db:5432 --timeout=30 --strict -- \
      alembic upgrade head && \
      python scripts/create_admin.py && \
      uvicorn app.main:app --host 0.0.0.0 --port 8000"
    restart: always
    
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./backend/init-test-db.sh:/docker-entrypoint-initdb.d/init-test-db.sh
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=duelo_de_plumas
    restart: always
    
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.prod
    ports:
      - "3001:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:3001/api
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data: 