"""Add AI judge fields

Revision ID: b28cf52140c9
Revises: 
Create Date: 2025-04-18 20:30:32.625661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b28cf52140c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('judge_type', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('ai_model', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ai_personality_prompt', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('ai_personality_prompt')
        batch_op.drop_column('ai_model')
        batch_op.drop_column('judge_type')

    # ### end Alembic commands ###
