"""Add contest_id to Vote model

Revision ID: bdf979b92b5b
Revises: 86a063b5ac5f
Create Date: 2025-04-18 16:05:38.762531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdf979b92b5b'
down_revision = '86a063b5ac5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contest_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('_judge_submission_uc', ['judge_id', 'submission_id'])
        batch_op.create_foreign_key(None, 'contest', ['contest_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('_judge_submission_uc', type_='unique')
        batch_op.drop_column('contest_id')

    # ### end Alembic commands ###
