"""Initial schema setup

Revision ID: 4af3f61ba2b7
Revises: 
Create Date: 2025-05-01 15:55:44.604259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4af3f61ba2b7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_evaluation', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('app_version',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    with op.batch_alter_table('ai_writer', schema=None) as batch_op:
        batch_op.alter_column('created_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('ai_writing_request', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('app_version',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    with op.batch_alter_table('contest', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('contest_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('required_judges',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.alter_column('submission_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('total_points',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('is_ai_generated',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('judge_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('app_version',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.alter_column('app_version',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('judge_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.alter_column('is_ai_generated',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('total_points',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('submission_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('contest', schema=None) as batch_op:
        batch_op.alter_column('required_judges',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('contest_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('ai_writing_request', schema=None) as batch_op:
        batch_op.alter_column('app_version',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('ai_writer', schema=None) as batch_op:
        batch_op.alter_column('created_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('ai_evaluation', schema=None) as batch_op:
        batch_op.alter_column('app_version',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
