"""Add contest restrictions flags

Revision ID: 826760318eb7
Revises: eab5c6370991
Create Date: 2025-05-03 09:21:38.643161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '826760318eb7'
down_revision: Union[str, None] = 'eab5c6370991'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted for SQLite batch mode ###

    # Batch 1: Add columns as nullable
    with op.batch_alter_table('contest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('limit_submissions_per_author', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('restrict_judges_as_authors', sa.Boolean(), nullable=True))

    # Update existing rows *after* columns are added
    op.execute('UPDATE contest SET limit_submissions_per_author = 0 WHERE limit_submissions_per_author IS NULL')
    op.execute('UPDATE contest SET restrict_judges_as_authors = 0 WHERE restrict_judges_as_authors IS NULL')

    # Batch 2: Alter columns to non-nullable and set server default
    with op.batch_alter_table('contest', schema=None) as batch_op:
        batch_op.alter_column('limit_submissions_per_author',
                              existing_type=sa.BOOLEAN(),
                              nullable=False,
                              server_default=sa.false()) # Set server_default here
        batch_op.alter_column('restrict_judges_as_authors',
                              existing_type=sa.BOOLEAN(),
                              nullable=False,
                              server_default=sa.false()) # Set server_default here

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contest', schema=None) as batch_op:
        batch_op.drop_column('restrict_judges_as_authors')
        batch_op.drop_column('limit_submissions_per_author')

    # ### end Alembic commands ###
