"""Add ai_debug_logs table for development debugging

Revision ID: ai_debug_logs_001
Revises: 558cd0c633c1
Create Date: 2024-01-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ai_debug_logs_001'
down_revision = '558cd0c633c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_debug_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('operation_type', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('contest_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.String(length=100), nullable=True),
    sa.Column('strategy_input', sa.Text(), nullable=True),
    sa.Column('llm_prompt', sa.Text(), nullable=True),
    sa.Column('llm_response', sa.Text(), nullable=True),
    sa.Column('parsed_output', sa.Text(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_debug_timestamp', 'ai_debug_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_ai_debug_logs_id'), 'ai_debug_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_debug_logs_id'), table_name='ai_debug_logs')
    op.drop_index('idx_ai_debug_timestamp', table_name='ai_debug_logs')
    op.drop_table('ai_debug_logs')
    # ### end Alembic commands ### 