"""Add credits to user and create cost_ledger table

Revision ID: afd526263dc8
Revises: dfbf9f5cc2b5
Create Date: 2025-05-03 22:52:02.578555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afd526263dc8'
down_revision: Union[str, None] = 'dfbf9f5cc2b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('credits_change', sa.Integer(), nullable=False),
    sa.Column('real_cost', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('resulting_balance', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cost_ledger'))
    )
    with op.batch_alter_table('cost_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cost_ledger_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_ledger_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_ledger_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credits', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('credits')

    with op.batch_alter_table('cost_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cost_ledger_user_id'))
        batch_op.drop_index(batch_op.f('ix_cost_ledger_timestamp'))
        batch_op.drop_index(batch_op.f('ix_cost_ledger_action_type'))

    op.drop_table('cost_ledger')
    # ### end Alembic commands ###
