"""Add AIWritingRequest model

Revision ID: e59581bc6818
Revises: d011884107ca
Create Date: 2025-05-02 20:11:50.741289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e59581bc6818'
down_revision: Union[str, None] = 'd011884107ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_writing_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('ai_writer_id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.Column('ai_model', sa.String(length=50), nullable=False),
    sa.Column('full_prompt', sa.Text(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('app_version', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['ai_writer_id'], ['ai_writer.id'], ),
    sa.ForeignKeyConstraint(['contest_id'], ['contest.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id')
    )
    with op.batch_alter_table('ai_writing_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_writing_request_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_writing_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_writing_request_timestamp'))

    op.drop_table('ai_writing_request')
    # ### end Alembic commands ###
