"""add_total_points_to_contest_text

Revision ID: f16882a77b6f
Revises: 567ebf97ae4a
Create Date: 2025-05-15 15:48:25.806693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f16882a77b6f'
down_revision = '567ebf97ae4a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contest_texts', sa.Column('total_points', sa.Integer(), nullable=True, default=0))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contest_texts', 'total_points')
    # ### end Alembic commands ### 